# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_OMAIII(object):
    def setupUi(self, OMAIII):
        OMAIII.setObjectName(_fromUtf8("OMAIII"))
        OMAIII.setWindowModality(QtCore.Qt.ApplicationModal)
        OMAIII.resize(818, 658)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OMAIII.sizePolicy().hasHeightForWidth())
        OMAIII.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(OMAIII)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.maintabs = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maintabs.setFont(font)
        self.maintabs.setTabPosition(QtGui.QTabWidget.West)
        self.maintabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.maintabs.setIconSize(QtCore.QSize(16, 16))
        self.maintabs.setElideMode(QtCore.Qt.ElideNone)
        self.maintabs.setObjectName(_fromUtf8("maintabs"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_config)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gb_save_load_project = QtGui.QGroupBox(self.tab_config)
        self.gb_save_load_project.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gb_save_load_project.setObjectName(_fromUtf8("gb_save_load_project"))
        self.gridLayout_24 = QtGui.QGridLayout(self.gb_save_load_project)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.save_project = QtGui.QPushButton(self.gb_save_load_project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_project.sizePolicy().hasHeightForWidth())
        self.save_project.setSizePolicy(sizePolicy)
        self.save_project.setObjectName(_fromUtf8("save_project"))
        self.gridLayout_24.addWidget(self.save_project, 0, 0, 1, 1)
        self.load_project = QtGui.QPushButton(self.gb_save_load_project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_project.sizePolicy().hasHeightForWidth())
        self.load_project.setSizePolicy(sizePolicy)
        self.load_project.setObjectName(_fromUtf8("load_project"))
        self.gridLayout_24.addWidget(self.load_project, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.gb_save_load_project, 1, 2, 1, 1)
        self.gb_serial_config = QtGui.QGroupBox(self.tab_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_serial_config.sizePolicy().hasHeightForWidth())
        self.gb_serial_config.setSizePolicy(sizePolicy)
        self.gb_serial_config.setMinimumSize(QtCore.QSize(250, 0))
        self.gb_serial_config.setObjectName(_fromUtf8("gb_serial_config"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gb_serial_config)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lb_serial_stopbits = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_stopbits.setObjectName(_fromUtf8("lb_serial_stopbits"))
        self.gridLayout_14.addWidget(self.lb_serial_stopbits, 3, 0, 1, 1)
        self.lb_serial_parity = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_parity.setObjectName(_fromUtf8("lb_serial_parity"))
        self.gridLayout_14.addWidget(self.lb_serial_parity, 2, 0, 1, 1)
        self.lb_serial_bytesize = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_bytesize.setObjectName(_fromUtf8("lb_serial_bytesize"))
        self.gridLayout_14.addWidget(self.lb_serial_bytesize, 4, 0, 1, 1)
        self.lb_serial_baudrate = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_baudrate.setObjectName(_fromUtf8("lb_serial_baudrate"))
        self.gridLayout_14.addWidget(self.lb_serial_baudrate, 1, 0, 1, 1)
        self.lb_serial_timeout = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_timeout.setObjectName(_fromUtf8("lb_serial_timeout"))
        self.gridLayout_14.addWidget(self.lb_serial_timeout, 5, 0, 1, 1)
        self.cbx_serial_port = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_port.setObjectName(_fromUtf8("cbx_serial_port"))
        self.gridLayout_14.addWidget(self.cbx_serial_port, 0, 2, 1, 1)
        self.sp_serial_timeout = QtGui.QSpinBox(self.gb_serial_config)
        self.sp_serial_timeout.setMinimum(1)
        self.sp_serial_timeout.setProperty("value", 2)
        self.sp_serial_timeout.setObjectName(_fromUtf8("sp_serial_timeout"))
        self.gridLayout_14.addWidget(self.sp_serial_timeout, 5, 2, 1, 1)
        self.lb_serial_port = QtGui.QLabel(self.gb_serial_config)
        self.lb_serial_port.setObjectName(_fromUtf8("lb_serial_port"))
        self.gridLayout_14.addWidget(self.lb_serial_port, 0, 0, 1, 1)
        self.cbx_serial_baudrates = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_baudrates.setObjectName(_fromUtf8("cbx_serial_baudrates"))
        self.gridLayout_14.addWidget(self.cbx_serial_baudrates, 1, 2, 1, 1)
        self.cbx_serial_parities = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_parities.setObjectName(_fromUtf8("cbx_serial_parities"))
        self.gridLayout_14.addWidget(self.cbx_serial_parities, 2, 2, 1, 1)
        self.cbx_serial_stopbits = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_stopbits.setObjectName(_fromUtf8("cbx_serial_stopbits"))
        self.gridLayout_14.addWidget(self.cbx_serial_stopbits, 3, 2, 1, 1)
        self.cbx_serial_bytesizes = QtGui.QComboBox(self.gb_serial_config)
        self.cbx_serial_bytesizes.setObjectName(_fromUtf8("cbx_serial_bytesizes"))
        self.gridLayout_14.addWidget(self.cbx_serial_bytesizes, 4, 2, 1, 1)
        self.gridLayout_13.addWidget(self.gb_serial_config, 0, 0, 1, 1)
        self.gb_monochromator_config = QtGui.QGroupBox(self.tab_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_monochromator_config.sizePolicy().hasHeightForWidth())
        self.gb_monochromator_config.setSizePolicy(sizePolicy)
        self.gb_monochromator_config.setObjectName(_fromUtf8("gb_monochromator_config"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gb_monochromator_config)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lb_monochromator_amplitude = QtGui.QLabel(self.gb_monochromator_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_monochromator_amplitude.sizePolicy().hasHeightForWidth())
        self.lb_monochromator_amplitude.setSizePolicy(sizePolicy)
        self.lb_monochromator_amplitude.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_monochromator_amplitude.setObjectName(_fromUtf8("lb_monochromator_amplitude"))
        self.gridLayout_9.addWidget(self.lb_monochromator_amplitude, 0, 2, 1, 1)
        self.le_monochromator_g2_lines = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g2_lines.setObjectName(_fromUtf8("le_monochromator_g2_lines"))
        self.gridLayout_9.addWidget(self.le_monochromator_g2_lines, 5, 1, 1, 1)
        self.le_monochromator_g3_amplitude = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g3_amplitude.setObjectName(_fromUtf8("le_monochromator_g3_amplitude"))
        self.gridLayout_9.addWidget(self.le_monochromator_g3_amplitude, 6, 2, 1, 1)
        self.lb_monochromator_grating_1 = QtGui.QLabel(self.gb_monochromator_config)
        self.lb_monochromator_grating_1.setObjectName(_fromUtf8("lb_monochromator_grating_1"))
        self.gridLayout_9.addWidget(self.lb_monochromator_grating_1, 4, 0, 1, 1)
        self.lb_monochromator_grating_2 = QtGui.QLabel(self.gb_monochromator_config)
        self.lb_monochromator_grating_2.setObjectName(_fromUtf8("lb_monochromator_grating_2"))
        self.gridLayout_9.addWidget(self.lb_monochromator_grating_2, 5, 0, 1, 1)
        self.lb_monochromator_grating_3 = QtGui.QLabel(self.gb_monochromator_config)
        self.lb_monochromator_grating_3.setObjectName(_fromUtf8("lb_monochromator_grating_3"))
        self.gridLayout_9.addWidget(self.lb_monochromator_grating_3, 6, 0, 1, 1)
        self.lb_monochromathor_lines_p_mm = QtGui.QLabel(self.gb_monochromator_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_monochromathor_lines_p_mm.sizePolicy().hasHeightForWidth())
        self.lb_monochromathor_lines_p_mm.setSizePolicy(sizePolicy)
        self.lb_monochromathor_lines_p_mm.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_monochromathor_lines_p_mm.setObjectName(_fromUtf8("lb_monochromathor_lines_p_mm"))
        self.gridLayout_9.addWidget(self.lb_monochromathor_lines_p_mm, 0, 1, 1, 1)
        self.le_monochromator_g1_amplitude = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g1_amplitude.setObjectName(_fromUtf8("le_monochromator_g1_amplitude"))
        self.gridLayout_9.addWidget(self.le_monochromator_g1_amplitude, 4, 2, 1, 1)
        self.le_monochromator_g3_lines = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g3_lines.setObjectName(_fromUtf8("le_monochromator_g3_lines"))
        self.gridLayout_9.addWidget(self.le_monochromator_g3_lines, 6, 1, 1, 1)
        self.le_monochromator_g1_lines = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g1_lines.setObjectName(_fromUtf8("le_monochromator_g1_lines"))
        self.gridLayout_9.addWidget(self.le_monochromator_g1_lines, 4, 1, 1, 1)
        self.le_monochromator_g2_amplitude = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g2_amplitude.setObjectName(_fromUtf8("le_monochromator_g2_amplitude"))
        self.gridLayout_9.addWidget(self.le_monochromator_g2_amplitude, 5, 2, 1, 1)
        self.lb_monochromator_resolution = QtGui.QLabel(self.gb_monochromator_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_monochromator_resolution.sizePolicy().hasHeightForWidth())
        self.lb_monochromator_resolution.setSizePolicy(sizePolicy)
        self.lb_monochromator_resolution.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_monochromator_resolution.setObjectName(_fromUtf8("lb_monochromator_resolution"))
        self.gridLayout_9.addWidget(self.lb_monochromator_resolution, 0, 3, 1, 1)
        self.lb_monochromator_factor = QtGui.QLabel(self.gb_monochromator_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_monochromator_factor.sizePolicy().hasHeightForWidth())
        self.lb_monochromator_factor.setSizePolicy(sizePolicy)
        self.lb_monochromator_factor.setObjectName(_fromUtf8("lb_monochromator_factor"))
        self.gridLayout_9.addWidget(self.lb_monochromator_factor, 0, 5, 1, 1)
        self.le_monochromator_g1_resolution = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g1_resolution.setObjectName(_fromUtf8("le_monochromator_g1_resolution"))
        self.gridLayout_9.addWidget(self.le_monochromator_g1_resolution, 4, 3, 1, 1)
        self.le_monochromator_g2_resolution = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g2_resolution.setObjectName(_fromUtf8("le_monochromator_g2_resolution"))
        self.gridLayout_9.addWidget(self.le_monochromator_g2_resolution, 5, 3, 1, 1)
        self.le_monochromator_g3_resolution = QtGui.QLineEdit(self.gb_monochromator_config)
        self.le_monochromator_g3_resolution.setObjectName(_fromUtf8("le_monochromator_g3_resolution"))
        self.gridLayout_9.addWidget(self.le_monochromator_g3_resolution, 6, 3, 1, 1)
        self.dsb_monochromator_g1_factor = QtGui.QDoubleSpinBox(self.gb_monochromator_config)
        self.dsb_monochromator_g1_factor.setObjectName(_fromUtf8("dsb_monochromator_g1_factor"))
        self.gridLayout_9.addWidget(self.dsb_monochromator_g1_factor, 4, 5, 1, 1)
        self.dsb_monochromator_g2_factor = QtGui.QDoubleSpinBox(self.gb_monochromator_config)
        self.dsb_monochromator_g2_factor.setObjectName(_fromUtf8("dsb_monochromator_g2_factor"))
        self.gridLayout_9.addWidget(self.dsb_monochromator_g2_factor, 5, 5, 1, 1)
        self.dsb_monochromator_g3_factor = QtGui.QDoubleSpinBox(self.gb_monochromator_config)
        self.dsb_monochromator_g3_factor.setObjectName(_fromUtf8("dsb_monochromator_g3_factor"))
        self.gridLayout_9.addWidget(self.dsb_monochromator_g3_factor, 6, 5, 1, 1)
        self.gridLayout_13.addWidget(self.gb_monochromator_config, 1, 0, 1, 2)
        self.gb_file_format = QtGui.QGroupBox(self.tab_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_file_format.sizePolicy().hasHeightForWidth())
        self.gb_file_format.setSizePolicy(sizePolicy)
        self.gb_file_format.setObjectName(_fromUtf8("gb_file_format"))
        self.gridLayout_22 = QtGui.QGridLayout(self.gb_file_format)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.lb_file_comment_position = QtGui.QLabel(self.gb_file_format)
        self.lb_file_comment_position.setObjectName(_fromUtf8("lb_file_comment_position"))
        self.gridLayout_22.addWidget(self.lb_file_comment_position, 2, 0, 1, 1)
        self.lb_file_column_separator = QtGui.QLabel(self.gb_file_format)
        self.lb_file_column_separator.setObjectName(_fromUtf8("lb_file_column_separator"))
        self.gridLayout_22.addWidget(self.lb_file_column_separator, 0, 0, 1, 1)
        self.cbx_file_separator = QtGui.QComboBox(self.gb_file_format)
        self.cbx_file_separator.setObjectName(_fromUtf8("cbx_file_separator"))
        self.cbx_file_separator.addItem(_fromUtf8(""), '\t')
        self.cbx_file_separator.addItem(_fromUtf8(""), ' ')
        self.cbx_file_separator.addItem(_fromUtf8(""), ',')
        self.cbx_file_separator.addItem(_fromUtf8(""), ';')
        self.gridLayout_22.addWidget(self.cbx_file_separator, 0, 1, 1, 1)
        self.lb_file_comments_string = QtGui.QLabel(self.gb_file_format)
        self.lb_file_comments_string.setObjectName(_fromUtf8("lb_file_comments_string"))
        self.gridLayout_22.addWidget(self.lb_file_comments_string, 1, 0, 1, 1)
        self.le_file_comment_string = QtGui.QLineEdit(self.gb_file_format)
        self.le_file_comment_string.setObjectName(_fromUtf8("le_file_comment_string"))
        self.gridLayout_22.addWidget(self.le_file_comment_string, 1, 1, 1, 1)

        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem, 3, 0, 1, 2)
        self.gridLayout_13.addWidget(self.gb_file_format, 0, 1, 1, 1)
        
        self.gb_plot_settings = QtGui.QGroupBox(self.tab_config)
        self.gb_plot_settings.setObjectName(_fromUtf8("gb_plot_settings"))
        self.gridLayout_23 = QtGui.QGridLayout(self.gb_plot_settings)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))

        self.chk_show_grid_lines = QtGui.QCheckBox(self.gb_plot_settings)
        self.chk_show_grid_lines.setObjectName(_fromUtf8("chk_show_grid_lines"))
        self.gridLayout_23.addWidget(self.chk_show_grid_lines, 3, 1, 1, 2)

        self.chk_show_plot_toolbar = QtGui.QCheckBox(self.gb_plot_settings)
        self.chk_show_plot_toolbar.setObjectName(_fromUtf8("chk_show_plot_toolbar"))
        self.gridLayout_23.addWidget(self.chk_show_plot_toolbar, 4, 1, 1, 1)

        self.gridLayout_13.addWidget(self.gb_plot_settings, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem2, 0, 3, 2, 1)
        self.maintabs.addTab(self.tab_config, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_control)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.toolBox_daq = QtGui.QToolBox(self.tab_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_daq.sizePolicy().hasHeightForWidth())
        self.toolBox_daq.setSizePolicy(sizePolicy)
        self.toolBox_daq.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox_daq.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox_daq.setAutoFillBackground(False)
        self.toolBox_daq.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox_daq.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox_daq.setLineWidth(1)
        self.toolBox_daq.setMidLineWidth(0)
        self.toolBox_daq.setObjectName(_fromUtf8("toolBox_daq"))
        self.daq_scan_settings = QtGui.QWidget()
        self.daq_scan_settings.setGeometry(QtCore.QRect(0, 0, 235, 536))
        self.daq_scan_settings.setObjectName(_fromUtf8("daq_scan_settings"))
        self.gridLayout_7 = QtGui.QGridLayout(self.daq_scan_settings)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gb_bkg = QtGui.QGroupBox(self.daq_scan_settings)
        self.gb_bkg.setObjectName(_fromUtf8("gb_bkg"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gb_bkg)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.le_bkg = QtGui.QLineEdit(self.gb_bkg)
        self.le_bkg.setObjectName(_fromUtf8("le_bkg"))
        self.gridLayout_6.addWidget(self.le_bkg, 0, 0, 1, 1)
        self.tlb_fo_bkg = QtGui.QToolButton(self.gb_bkg)
        self.tlb_fo_bkg.setStyleSheet(_fromUtf8("border-color: rgb(0, 170, 255);"))
        self.tlb_fo_bkg.setObjectName(_fromUtf8("tlb_fo_bkg"))
        self.gridLayout_6.addWidget(self.tlb_fo_bkg, 0, 1, 1, 1)
        self.rb_bkg_auto = QtGui.QRadioButton(self.gb_bkg)
        self.rb_bkg_auto.setObjectName(_fromUtf8("rb_bkg_auto"))
        self.gridLayout_6.addWidget(self.rb_bkg_auto, 2, 0, 1, 2)
        self.rb_bkg_plot = QtGui.QRadioButton(self.gb_bkg)
        self.rb_bkg_plot.setObjectName(_fromUtf8("rb_bkg_plot"))
        self.gridLayout_6.addWidget(self.rb_bkg_plot, 3, 0, 1, 2)
        self.pb_subst_bkg = QtGui.QPushButton(self.gb_bkg)
        self.pb_subst_bkg.setStyleSheet(_fromUtf8(""))
        self.pb_subst_bkg.setObjectName(_fromUtf8("pb_subst_bkg"))
        self.gridLayout_6.addWidget(self.pb_subst_bkg, 1, 0, 1, 2)
        self.rb_bkg_save_only = QtGui.QRadioButton(self.gb_bkg)
        self.rb_bkg_save_only.setObjectName(_fromUtf8("rb_bkg_save_only"))
        self.gridLayout_6.addWidget(self.rb_bkg_save_only, 4, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gb_bkg, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 5, 0, 1, 1)
        self.ScanSequence = QtGui.QGroupBox(self.daq_scan_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScanSequence.sizePolicy().hasHeightForWidth())
        self.ScanSequence.setSizePolicy(sizePolicy)
        self.ScanSequence.setObjectName(_fromUtf8("ScanSequence"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ScanSequence)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.le_damode = QtGui.QLineEdit(self.ScanSequence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_damode.sizePolicy().hasHeightForWidth())
        self.le_damode.setSizePolicy(sizePolicy)
        self.le_damode.setObjectName(_fromUtf8("le_damode"))
        self.gridLayout_3.addWidget(self.le_damode, 3, 0, 1, 1)
        self.lbl_damode = QtGui.QLabel(self.ScanSequence)
        self.lbl_damode.setObjectName(_fromUtf8("lbl_damode"))
        self.gridLayout_3.addWidget(self.lbl_damode, 3, 1, 1, 1)
        self.le_exposuretime = QtGui.QLineEdit(self.ScanSequence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_exposuretime.sizePolicy().hasHeightForWidth())
        self.le_exposuretime.setSizePolicy(sizePolicy)
        self.le_exposuretime.setObjectName(_fromUtf8("le_exposuretime"))
        self.gridLayout_3.addWidget(self.le_exposuretime, 0, 0, 1, 1)
        self.lbl_exposuretime = QtGui.QLabel(self.ScanSequence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_exposuretime.sizePolicy().hasHeightForWidth())
        self.lbl_exposuretime.setSizePolicy(sizePolicy)
        self.lbl_exposuretime.setObjectName(_fromUtf8("lbl_exposuretime"))
        self.gridLayout_3.addWidget(self.lbl_exposuretime, 0, 1, 1, 1)
        self.le_scansnumber = QtGui.QLineEdit(self.ScanSequence)
        self.le_scansnumber.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_scansnumber.sizePolicy().hasHeightForWidth())
        self.le_scansnumber.setSizePolicy(sizePolicy)
        self.le_scansnumber.setObjectName(_fromUtf8("le_scansnumber"))
        self.gridLayout_3.addWidget(self.le_scansnumber, 1, 0, 1, 1)
        self.lbl_scansnumber = QtGui.QLabel(self.ScanSequence)
        self.lbl_scansnumber.setObjectName(_fromUtf8("lbl_scansnumber"))
        self.gridLayout_3.addWidget(self.lbl_scansnumber, 1, 1, 1, 1)
        self.le_ignoredscans = QtGui.QLineEdit(self.ScanSequence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ignoredscans.sizePolicy().hasHeightForWidth())
        self.le_ignoredscans.setSizePolicy(sizePolicy)
        self.le_ignoredscans.setObjectName(_fromUtf8("le_ignoredscans"))
        self.gridLayout_3.addWidget(self.le_ignoredscans, 2, 0, 1, 1)
        self.lbl_ignoredscans = QtGui.QLabel(self.ScanSequence)
        self.lbl_ignoredscans.setObjectName(_fromUtf8("lbl_ignoredscans"))
        self.gridLayout_3.addWidget(self.lbl_ignoredscans, 2, 1, 1, 1)
        self.le_detectortemp = QtGui.QLineEdit(self.ScanSequence)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_detectortemp.sizePolicy().hasHeightForWidth())
        self.le_detectortemp.setSizePolicy(sizePolicy)
        self.le_detectortemp.setObjectName(_fromUtf8("le_detectortemp"))
        self.gridLayout_3.addWidget(self.le_detectortemp, 4, 0, 1, 1)
        self.lbl_detectortemp = QtGui.QLabel(self.ScanSequence)
        self.lbl_detectortemp.setObjectName(_fromUtf8("lbl_detectortemp"))
        self.gridLayout_3.addWidget(self.lbl_detectortemp, 4, 1, 1, 1)
        self.btn_check = QtGui.QPushButton(self.ScanSequence)
        self.btn_check.setStyleSheet(_fromUtf8(""))
        self.btn_check.setObjectName(_fromUtf8("btn_check"))
        self.gridLayout_3.addWidget(self.btn_check, 5, 0, 1, 2)
        self.btn_update = QtGui.QPushButton(self.ScanSequence)
        self.btn_update.setStyleSheet(_fromUtf8(""))
        self.btn_update.setObjectName(_fromUtf8("btn_update"))
        self.gridLayout_3.addWidget(self.btn_update, 6, 0, 1, 2)
        self.gridLayout_7.addWidget(self.ScanSequence, 0, 0, 1, 1)
        self.gb_scanloop = QtGui.QGroupBox(self.daq_scan_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_scanloop.sizePolicy().hasHeightForWidth())
        self.gb_scanloop.setSizePolicy(sizePolicy)
        self.gb_scanloop.setObjectName(_fromUtf8("gb_scanloop"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_scanloop)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lb_loop = QtGui.QLabel(self.gb_scanloop)
        self.lb_loop.setObjectName(_fromUtf8("lb_loop"))
        self.gridLayout_4.addWidget(self.lb_loop, 0, 0, 1, 1)
        self.sp_loop = QtGui.QSpinBox(self.gb_scanloop)
        self.sp_loop.setMaximum(999)
        self.sp_loop.setProperty("value", 1)
        self.sp_loop.setObjectName(_fromUtf8("sp_loop"))
        self.gridLayout_4.addWidget(self.sp_loop, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gb_scanloop, 4, 0, 1, 1)
        self.gb_scan_type = QtGui.QGroupBox(self.daq_scan_settings)
        self.gb_scan_type.setObjectName(_fromUtf8("gb_scan_type"))
        self.gridLayout_25 = QtGui.QGridLayout(self.gb_scan_type)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.rb_background = QtGui.QRadioButton(self.gb_scan_type)
        self.rb_background.setObjectName(_fromUtf8("rb_background"))
        self.gridLayout_25.addWidget(self.rb_background, 1, 0, 1, 1)
        self.rb_spectrum = QtGui.QRadioButton(self.gb_scan_type)
        self.rb_spectrum.setObjectName(_fromUtf8("rb_spectrum"))
        self.gridLayout_25.addWidget(self.rb_spectrum, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gb_scan_type, 1, 0, 1, 1)
        
        self.toolBox_daq.addItem(self.daq_scan_settings, _fromUtf8(""))
        
        self.gb_autoSave = QtGui.QGroupBox(self.daq_scan_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_autoSave.sizePolicy().hasHeightForWidth())
        self.gb_autoSave.setSizePolicy(sizePolicy)
        self.gb_autoSave.setMinimumSize(QtCore.QSize(0, 0))
        self.gb_autoSave.setMaximumSize(QtCore.QSize(240, 16777215))
        self.gb_autoSave.setObjectName(_fromUtf8("gb_autoSave"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gb_autoSave)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.chk_autosave = QtGui.QCheckBox(self.gb_autoSave)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_autosave.sizePolicy().hasHeightForWidth())
        self.chk_autosave.setSizePolicy(sizePolicy)
        self.chk_autosave.setObjectName(_fromUtf8("chk_autosave"))
        self.gridLayout_8.addWidget(self.chk_autosave, 0, 0, 1, 1)
        self.lbl_basename = QtGui.QLabel(self.gb_autoSave)
        self.lbl_basename.setObjectName(_fromUtf8("lbl_basename"))
        self.gridLayout_8.addWidget(self.lbl_basename, 1, 0, 1, 1)
        self.le_basename = QtGui.QLineEdit(self.gb_autoSave)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_basename.sizePolicy().hasHeightForWidth())
        self.le_basename.setSizePolicy(sizePolicy)
        self.le_basename.setObjectName(_fromUtf8("le_basename"))
        self.gridLayout_8.addWidget(self.le_basename, 2, 0, 1, 1)
        self.tlb_basename = QtGui.QToolButton(self.gb_autoSave)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tlb_basename.sizePolicy().hasHeightForWidth())
        self.tlb_basename.setSizePolicy(sizePolicy)
        self.tlb_basename.setObjectName(_fromUtf8("tlb_basename"))
        self.gridLayout_8.addWidget(self.tlb_basename, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gb_autoSave, 2, 0, 1, 2)

        self.daq_monochromator_info = QtGui.QWidget()
        self.daq_monochromator_info.setGeometry(QtCore.QRect(0, 0, 155, 185))
        self.daq_monochromator_info.setObjectName(_fromUtf8("daq_monochromator_info"))
        self.gridLayout_2 = QtGui.QGridLayout(self.daq_monochromator_info)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.daq_lbl_counter = QtGui.QLabel(self.daq_monochromator_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_lbl_counter.sizePolicy().hasHeightForWidth())
        self.daq_lbl_counter.setSizePolicy(sizePolicy)
        self.daq_lbl_counter.setObjectName(_fromUtf8("daq_lbl_counter"))
        self.gridLayout_2.addWidget(self.daq_lbl_counter, 1, 0, 1, 2)
        self.daq_lbl_grating = QtGui.QLabel(self.daq_monochromator_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_lbl_grating.sizePolicy().hasHeightForWidth())
        self.daq_lbl_grating.setSizePolicy(sizePolicy)
        self.daq_lbl_grating.setObjectName(_fromUtf8("daq_lbl_grating"))
        self.gridLayout_2.addWidget(self.daq_lbl_grating, 0, 0, 1, 1)
        self.daq_sp_monochromator_counter = QtGui.QSpinBox(self.daq_monochromator_info)
        self.daq_sp_monochromator_counter.setMaximum(999)
        self.daq_sp_monochromator_counter.setSingleStep(1)
        self.daq_sp_monochromator_counter.setObjectName(_fromUtf8("daq_sp_monochromator_counter"))
        self.gridLayout_2.addWidget(self.daq_sp_monochromator_counter, 1, 2, 1, 2)
        self.daq_pt_grating_info = QtGui.QPlainTextEdit(self.daq_monochromator_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_pt_grating_info.sizePolicy().hasHeightForWidth())
        self.daq_pt_grating_info.setSizePolicy(sizePolicy)
        self.daq_pt_grating_info.setObjectName(_fromUtf8("daq_pt_grating_info"))
        self.gridLayout_2.addWidget(self.daq_pt_grating_info, 5, 0, 1, 4)
        self.daq_lbl_grating_info = QtGui.QLabel(self.daq_monochromator_info)
        self.daq_lbl_grating_info.setObjectName(_fromUtf8("daq_lbl_grating_info"))
        self.gridLayout_2.addWidget(self.daq_lbl_grating_info, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 4)
        self.daq_cbx_monochromator_grating = QtGui.QComboBox(self.daq_monochromator_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_cbx_monochromator_grating.sizePolicy().hasHeightForWidth())
        self.daq_cbx_monochromator_grating.setSizePolicy(sizePolicy)
        self.daq_cbx_monochromator_grating.setObjectName(_fromUtf8("daq_cbx_monochromator_grating"))
        self.daq_cbx_monochromator_grating.addItem(_fromUtf8(""), 'g1')
        self.daq_cbx_monochromator_grating.addItem(_fromUtf8(""), 'g2')
        self.daq_cbx_monochromator_grating.addItem(_fromUtf8(""), 'g3')
        self.gridLayout_2.addWidget(self.daq_cbx_monochromator_grating, 0, 2, 1, 2)
        
        
        self.toolBox_daq.addItem(self.daq_monochromator_info, _fromUtf8(""))
        self.daq_plot_settings = QtGui.QWidget()
        self.daq_plot_settings.setGeometry(QtCore.QRect(0, 0, 176, 197))
        self.daq_plot_settings.setObjectName(_fromUtf8("daq_plot_settings"))
        self.gridLayout_21 = QtGui.QGridLayout(self.daq_plot_settings)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        
        self.daq_plot_cursors = QtGui.QGroupBox(self.daq_plot_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_plot_cursors.sizePolicy().hasHeightForWidth())
        self.daq_plot_cursors.setSizePolicy(sizePolicy)
        self.daq_plot_cursors.setObjectName(_fromUtf8("daq_plot_cursors"))
        self.gridLayout_20 = QtGui.QGridLayout(self.daq_plot_cursors)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.daq_plot_cursor_add = QtGui.QPushButton(self.daq_plot_cursors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_plot_cursor_add.sizePolicy().hasHeightForWidth())
        self.daq_plot_cursor_add.setSizePolicy(sizePolicy)
        self.daq_plot_cursor_add.setObjectName(_fromUtf8("daq_plot_cursor_add"))
        self.gridLayout_20.addWidget(self.daq_plot_cursor_add, 0, 0, 1, 1)
        self.daq_plot_cursor_remove = QtGui.QPushButton(self.daq_plot_cursors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_plot_cursor_remove.sizePolicy().hasHeightForWidth())
        self.daq_plot_cursor_remove.setSizePolicy(sizePolicy)
        self.daq_plot_cursor_remove.setObjectName(_fromUtf8("daq_plot_cursor_remove"))
        self.gridLayout_20.addWidget(self.daq_plot_cursor_remove, 0, 1, 1, 1)
        self.daq_plot_cursor_list = QtGui.QListView(self.daq_plot_cursors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_plot_cursor_list.sizePolicy().hasHeightForWidth())
        self.daq_plot_cursor_list.setSizePolicy(sizePolicy)
        self.daq_plot_cursor_list.setObjectName(_fromUtf8("daq_plot_cursor_list"))
        self.gridLayout_20.addWidget(self.daq_plot_cursor_list, 1, 0, 1, 2)
        self.gridLayout_21.addWidget(self.daq_plot_cursors, 1, 0, 1, 1)
        self.toolBox_daq.addItem(self.daq_plot_settings, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.toolBox_daq, 1, 0, 5, 1)
        spacerItem6 = QtGui.QSpacerItem(448, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 1, 1, 1, 1)
        self.daq_main_plot = QtGui.QGroupBox(self.tab_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_main_plot.sizePolicy().hasHeightForWidth())
        self.daq_main_plot.setSizePolicy(sizePolicy)
        self.daq_main_plot.setFlat(False)
        self.daq_main_plot.setObjectName(_fromUtf8("daq_main_plot"))
        self.gridLayout_10.addWidget(self.daq_main_plot, 2, 1, 1, 1)
        self.btn_run = QtGui.QPushButton(self.tab_control)
        self.btn_run.setMinimumSize(QtCore.QSize(0, 64))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_run.setFont(font)
        self.btn_run.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_run.setStyleSheet(_fromUtf8(""))
        self.btn_run.setIconSize(QtCore.QSize(50, 50))
        self.btn_run.setObjectName(_fromUtf8("btn_run"))
        self.gridLayout_10.addWidget(self.btn_run, 6, 0, 1, 1)
        self.maintabs.addTab(self.tab_control, _fromUtf8(""))
        self.tab_analyse = QtGui.QWidget()
        self.tab_analyse.setObjectName(_fromUtf8("tab_analyse"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_analyse)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.da_tolbox = QtGui.QToolBox(self.tab_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.da_tolbox.sizePolicy().hasHeightForWidth())
        self.da_tolbox.setSizePolicy(sizePolicy)
        self.da_tolbox.setMinimumSize(QtCore.QSize(250, 0))
        self.da_tolbox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.da_tolbox.setObjectName(_fromUtf8("da_tolbox"))
        self.workspace = QtGui.QWidget()
        self.workspace.setGeometry(QtCore.QRect(0, 0, 190, 118))
        self.workspace.setObjectName(_fromUtf8("workspace"))
        self.gridLayout_12 = QtGui.QGridLayout(self.workspace)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.da_list_files = QtGui.QListWidget(self.workspace)
        self.da_list_files.setObjectName(_fromUtf8("da_list_files"))

        self.gridLayout_12.addWidget(self.da_list_files, 2, 0, 1, 2)


        self.da_tolbox.addItem(self.workspace, _fromUtf8(""))
        self.da_plot_settings = QtGui.QWidget()
        self.da_plot_settings.setGeometry(QtCore.QRect(0, 0, 229, 275))
        self.da_plot_settings.setObjectName(_fromUtf8("da_plot_settings"))
        self.gridLayout_18 = QtGui.QGridLayout(self.da_plot_settings)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))

        self.da_plot_cursos = QtGui.QGroupBox(self.da_plot_settings)
        self.da_plot_cursos.setObjectName(_fromUtf8("da_plot_cursos"))
        self.gridLayout_15 = QtGui.QGridLayout(self.da_plot_cursos)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.da_plot_cursors_add = QtGui.QPushButton(self.da_plot_cursos)
        self.da_plot_cursors_add.setObjectName(_fromUtf8("da_plot_cursors_add"))
        self.gridLayout_15.addWidget(self.da_plot_cursors_add, 0, 0, 1, 1)
        self.da_plot_cursors_remove = QtGui.QPushButton(self.da_plot_cursos)
        self.da_plot_cursors_remove.setObjectName(_fromUtf8("da_plot_cursors_remove"))
        self.gridLayout_15.addWidget(self.da_plot_cursors_remove, 0, 1, 1, 1)
        self.da_plot_cursors_list = QtGui.QListView(self.da_plot_cursos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.da_plot_cursors_list.sizePolicy().hasHeightForWidth())
        self.da_plot_cursors_list.setSizePolicy(sizePolicy)
        self.da_plot_cursors_list.setObjectName(_fromUtf8("da_plot_cursors_list"))
        self.gridLayout_15.addWidget(self.da_plot_cursors_list, 1, 0, 1, 2)
        self.gridLayout_18.addWidget(self.da_plot_cursos, 2, 0, 1, 1)
        self.da_tolbox.addItem(self.da_plot_settings, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.da_tolbox, 0, 0, 2, 1)
        self.gb_da_plot = QtGui.QGroupBox(self.tab_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_da_plot.sizePolicy().hasHeightForWidth())
        self.gb_da_plot.setSizePolicy(sizePolicy)
        self.gb_da_plot.setObjectName(_fromUtf8("gb_da_plot"))
        self.gridLayout_11.addWidget(self.gb_da_plot, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(450, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 1, 1, 1, 1)
        self.maintabs.addTab(self.tab_analyse, _fromUtf8(""))
        self.gridLayout.addWidget(self.maintabs, 0, 0, 1, 1)
        OMAIII.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OMAIII)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        OMAIII.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OMAIII)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OMAIII.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(OMAIII)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.actionSave = QtGui.QAction(OMAIII)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.lbl_damode.setBuddy(self.le_damode)
        self.lbl_exposuretime.setBuddy(self.le_exposuretime)
        self.lbl_scansnumber.setBuddy(self.le_scansnumber)
        self.lbl_ignoredscans.setBuddy(self.le_ignoredscans)
        self.lbl_detectortemp.setBuddy(self.le_detectortemp)
        self.lbl_basename.setBuddy(self.le_basename)

        self.retranslateUi(OMAIII)
        self.maintabs.setCurrentIndex(0)
        self.toolBox_daq.setCurrentIndex(0)
        self.da_tolbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OMAIII)

        from pyoma.ploter.qtmatplotlib import canvas as PlotCanvas
        from pyoma.ploter.qtmatplotlib import NavigationToolbar
        # Inicializando base de ploteo para daq mainplot DAQ Control tab
        self.vbl_daq_main_plot = QtGui.QVBoxLayout(self.daq_main_plot)
        self.daq_maincanvas = PlotCanvas(self.daq_main_plot)
        self.daq_maincanvas.axes.set_xlim(0,1024)
        self.daq_maincanvas.axes.set_xlabel('Pixel')
        self.daq_maincanvas.axes.set_ylabel('Counts')
        self.vbl_daq_main_plot.insertWidget(0, self.daq_maincanvas)
        self.daq_maintb = NavigationToolbar(self.daq_maincanvas, self.daq_main_plot)
        self.vbl_daq_main_plot.insertWidget(1, self.daq_maintb)

        # Inicializando base de ploteo para daq mainplot Data Analisys Tab
        self.vbl_gb_da_plot = QtGui.QVBoxLayout(self.gb_da_plot)
        self.da_maincanvas = PlotCanvas(self.gb_da_plot)
        self.da_maincanvas.axes.set_xlim(0,1024)
        self.da_maincanvas.axes.set_xlabel('Pixel')
        self.da_maincanvas.axes.set_ylabel('Counts')
        self.vbl_gb_da_plot.insertWidget(0, self.da_maincanvas)
        self.da_maintb = NavigationToolbar(self.da_maincanvas, self.gb_da_plot)
        self.vbl_gb_da_plot.insertWidget(1, self.da_maintb)

        self.retranslateUi(OMAIII)
        self.actionQuit.triggered.connect(QtGui.qApp.quit)
        self.maintabs.setCurrentIndex(0)
        self.maintabs.setTabEnabled(1,False)
        self.maintabs.setTabEnabled(2,False)
        self.toolBox_daq.setCurrentIndex(0)
        self.da_tolbox.setCurrentIndex(0)
        # QtCore.QMetaObject.connectSlotsByName(OMAIII)

    def retranslateUi(self, OMAIII):
        OMAIII.setWindowTitle(_translate("OMAIII", "OMAIII - Data Adquisitor", None))
        self.gb_save_load_project.setTitle(_translate("OMAIII", "Save/Load Project", None))
        self.save_project.setText(_translate("OMAIII", "Save", None))
        self.load_project.setText(_translate("OMAIII", "Load", None))
        self.gb_serial_config.setTitle(_translate("OMAIII", "RS232 Interface", None))
        self.lb_serial_stopbits.setText(_translate("OMAIII", "Stopbits", None))
        self.lb_serial_parity.setText(_translate("OMAIII", "Parity", None))
        self.lb_serial_bytesize.setText(_translate("OMAIII", "ByteSize", None))
        self.lb_serial_baudrate.setText(_translate("OMAIII", "Baudrate", None))
        self.lb_serial_timeout.setText(_translate("OMAIII", "Timeout", None))
        self.lb_serial_port.setText(_translate("OMAIII", "Serail Port", None))
        self.gb_monochromator_config.setTitle(_translate("OMAIII", "Monochromator", None))
        self.lb_monochromator_amplitude.setText(_translate("OMAIII", "Amplitude", None))
        self.lb_monochromator_grating_1.setText(_translate("OMAIII", "Grating 1", None))
        self.lb_monochromator_grating_2.setText(_translate("OMAIII", "Grating 2", None))
        self.lb_monochromator_grating_3.setText(_translate("OMAIII", "Grating 3", None))
        self.lb_monochromathor_lines_p_mm.setText(_translate("OMAIII", "Lines/mm ", None))
        self.lb_monochromator_resolution.setText(_translate("OMAIII", "Resolution", None))
        self.lb_monochromator_factor.setText(_translate("OMAIII", "Factor divition", None))
        self.gb_file_format.setTitle(_translate("OMAIII", "File Format", None))
        self.lb_file_column_separator.setText(_translate("OMAIII", "Column separator", None))
        self.cbx_file_separator.setItemText(0, _translate("OMAIII", "Tab", None))
        self.cbx_file_separator.setItemText(1, _translate("OMAIII", "Space", None))
        self.cbx_file_separator.setItemText(2, _translate("OMAIII", "Colon", None))
        self.cbx_file_separator.setItemText(3, _translate("OMAIII", "Semi Colon", None))
        self.daq_cbx_monochromator_grating.setItemText(0, _translate("OMAIII", 'Grating 1', None))
        self.daq_cbx_monochromator_grating.setItemText(1, _translate("OMAIII", 'Grating 2', None))
        self.daq_cbx_monochromator_grating.setItemText(2, _translate("OMAIII", 'Grating 3', None))
        self.lb_file_comments_string.setText(_translate("OMAIII", "Comment string", None))
        self.gb_plot_settings.setTitle(_translate("OMAIII", "Plot Settings", None))
        self.chk_show_grid_lines.setText(_translate("OMAIII", "Show grid lines", None))
        self.chk_show_plot_toolbar.setText(_translate("OMAIII", "Show plot toolbar", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_config), _translate("OMAIII", "Configuration", None))
        self.gb_bkg.setTitle(_translate("OMAIII", "Background", None))
        self.tlb_fo_bkg.setText(_translate("OMAIII", "...", None))
        self.rb_bkg_auto.setText(_translate("OMAIII", "Auto background substraction", None))
        self.rb_bkg_plot.setText(_translate("OMAIII", "Plot background and spectra", None))
        self.pb_subst_bkg.setText(_translate("OMAIII", "Substract", None))
        self.rb_bkg_save_only.setText(_translate("OMAIII", "Save only", None))
        self.ScanSequence.setTitle(_translate("OMAIII", "OMA Configuration", None))
        self.lbl_damode.setText(_translate("OMAIII", "DA Mode", None))
        self.lbl_exposuretime.setText(_translate("OMAIII", "Exposure Time", None))
        self.lbl_scansnumber.setText(_translate("OMAIII", "N° Scans", None))
        self.lbl_ignoredscans.setText(_translate("OMAIII", "Ignored Scans", None))
        self.lbl_detectortemp.setText(_translate("OMAIII", "Temperature", None))
        self.btn_check.setText(_translate("OMAIII", "Check", None))
        self.btn_update.setText(_translate("OMAIII", "Update", None))
        self.gb_scanloop.setTitle(_translate("OMAIII", "Scans Loop", None))
        self.lb_loop.setText(_translate("OMAIII", "Number of consecutive scans. ", None))
        self.gb_scan_type.setTitle(_translate("OMAIII", "Scan type", None))
        self.rb_background.setText(_translate("OMAIII", "Background", None))
        self.rb_spectrum.setText(_translate("OMAIII", "Spectrum", None))
        self.toolBox_daq.setItemText(self.toolBox_daq.indexOf(self.daq_scan_settings), _translate("OMAIII", "OMAIII Scan Settings", None))


        self.gb_autoSave.setTitle(_translate("OMAIII", "Auto Save", None))
        self.chk_autosave.setText(_translate("OMAIII", "Enable", None))
        self.lbl_basename.setText(_translate("OMAIII", "Base Name", None))
        self.tlb_basename.setText(_translate("OMAIII", "...", None))

        self.daq_lbl_counter.setText(_translate("OMAIII", "Counter", None))
        self.daq_lbl_grating.setText(_translate("OMAIII", "Red", None))
        self.daq_lbl_grating_info.setText(_translate("OMAIII", "Grating info", None))
        self.toolBox_daq.setItemText(self.toolBox_daq.indexOf(self.daq_monochromator_info), _translate("OMAIII", "Monochromator Info", None))
        self.toolBox_daq.setItemText(self.toolBox_daq.indexOf(self.daq_plot_settings), _translate("OMAIII", "Plot Settings", None))
        self.daq_plot_cursors.setTitle(_translate("OMAIII", "Cursors", None))
        self.daq_plot_cursor_add.setText(_translate("OMAIII", "Add", None))
        self.daq_plot_cursor_remove.setText(_translate("OMAIII", "Remove", None))

        self.daq_main_plot.setTitle(_translate("OMAIII", "Data Adquisition Plot", None))
        self.btn_run.setText(_translate("OMAIII", "RUN", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_control), _translate("OMAIII", "Control DAQ", None))
        __sortingEnabled = self.da_list_files.isSortingEnabled()
        self.da_list_files.setSortingEnabled(False)
        self.da_list_files.setSortingEnabled(__sortingEnabled)
        self.da_tolbox.setItemText(self.da_tolbox.indexOf(self.workspace), _translate("OMAIII", "File list", None))

        self.da_plot_cursos.setTitle(_translate("OMAIII", "Cursors", None))
        self.da_plot_cursors_add.setText(_translate("OMAIII", "Add", None))
        self.da_plot_cursors_remove.setText(_translate("OMAIII", "Remove", None))
        self.da_tolbox.setItemText(self.da_tolbox.indexOf(self.da_plot_settings), _translate("OMAIII", "Plot Settings", None))
        self.gb_da_plot.setTitle(_translate("OMAIII", "Data Analyse Plot", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_analyse), _translate("OMAIII", "Data Analyse ", None))
        self.menuFile.setTitle(_translate("OMAIII", "File", None))
        self.actionQuit.setText(_translate("OMAIII", "Quit", None))
        self.actionSave.setText(_translate("OMAIII", "Save", None))


